import type { DetectedStack } from '../types'

export function buildClaudeMd(stack: DetectedStack): string {
  const { language, frameworks } = stack
  const fw = frameworks.join(', ') || language

  return `# 프로젝트 가이드라인 (Auto-generated by AI Workspace Configurator)

## 기술 스택
- **언어**: ${language}
- **프레임워크**: ${fw || '감지되지 않음'}

## 빌드 명령어
${buildCommands(stack)}

## 코드 규칙

### 타이핑
- \`any\` 타입 사용 금지. 불확실한 타입은 \`unknown\` 후 narrowing.
- 모든 Props/API 응답 타입은 명시적으로 정의.

### 컴포넌트 원칙
- 단일 책임: 컴포넌트 하나는 하나의 역할만.
- 150줄 초과 시 분리.
- 비즈니스 로직은 커스텀 훅으로 분리.

### 보안
- API 키는 환경변수로만. 코드 하드코딩 절대 금지.
- 사용자 입력은 항상 검증.
${frameworkRules(stack)}
`
}

function buildCommands(stack: DetectedStack): string {
  if (stack.manifests.includes('package.json')) {
    const hasDev = stack.frameworks.includes('Vite') || stack.frameworks.includes('Next.js')
    return `\`\`\`bash
npm run dev      # 개발 서버
npm run build    # 프로덕션 빌드
npm run lint     # 린트
npm test         # 테스트
\`\`\``
  }
  if (stack.manifests.includes('requirements.txt') || stack.manifests.includes('pyproject.toml')) {
    return `\`\`\`bash
python -m uvicorn main:app --reload   # 개발 서버 (FastAPI)
python manage.py runserver            # 개발 서버 (Django)
pytest                                # 테스트
\`\`\``
  }
  if (stack.manifests.includes('go.mod')) {
    return `\`\`\`bash
go run .         # 실행
go build .       # 빌드
go test ./...    # 테스트
\`\`\``
  }
  return '프로젝트 빌드 명령어를 직접 입력해주세요.'
}

function frameworkRules(stack: DetectedStack): string {
  const rules: string[] = []
  if (stack.frameworks.includes('React')) {
    rules.push('\n### React\n- 함수형 컴포넌트 + Hooks만 사용.\n- 사이드이펙트는 `useEffect`로 격리.')
  }
  if (stack.frameworks.includes('Next.js')) {
    rules.push('\n### Next.js\n- Server Component / Client Component 경계를 명확히.\n- 환경변수는 `NEXT_PUBLIC_` 규칙 준수.')
  }
  if (stack.frameworks.includes('Firebase')) {
    rules.push('\n### Firebase\n- Firebase SDK 직접 호출은 `services/firebase.ts`에서만.\n- 컴포넌트에서 직접 호출 금지.')
  }
  return rules.join('\n')
}
