import * as fs from 'fs'
import * as path from 'path'
import type { DetectedStack } from '@ai-workspace-configurator/core'

// Frameworks that don't significantly change generated content
const TOOLING_FW = new Set(['Tailwind CSS', 'Vite', 'Testing Library'])

export interface GeneratedMetadata {
  lang: string
  fw: string[]
  date: string
}

export interface StalenessResult {
  isStale: boolean
  newFrameworks: string[]  // frameworks in current stack not in saved metadata
  languageChanged: boolean // e.g. JavaScript → TypeScript migration
  daysSince: number        // days since last generation
}

/**
 * Reads the machine-readable metadata comment from the first line of CLAUDE.md.
 * Returns null if the file doesn't exist or wasn't generated by this extension.
 */
export function readGeneratedMetadata(workspaceRoot: string): GeneratedMetadata | null {
  const claudePath = path.join(workspaceRoot, 'CLAUDE.md')
  if (!fs.existsSync(claudePath)) return null

  try {
    const firstLine = fs.readFileSync(claudePath, 'utf-8').split('\n')[0]
    const match = firstLine.match(/^<!-- ai-workspace-configurator ({.*}) -->$/)
    if (!match) return null
    const parsed = JSON.parse(match[1]) as Partial<GeneratedMetadata>
    if (!parsed.lang || !Array.isArray(parsed.fw) || !parsed.date) return null
    return parsed as GeneratedMetadata
  } catch {
    return null
  }
}

/**
 * Compares the current detected stack against the last-generated metadata.
 * Only significant new additions (not removals) are flagged as stale —
 * we don't want to nag users for removing a dependency.
 */
export function checkStaleness(current: DetectedStack, meta: GeneratedMetadata): StalenessResult {
  const significantCurrent = current.frameworks.filter((fw) => !TOOLING_FW.has(fw))
  const newFrameworks = significantCurrent.filter((fw) => !meta.fw.includes(fw))

  // Language change only counts when previous was not Unknown (manually set via QuickPick)
  const languageChanged =
    meta.lang !== 'Unknown' &&
    current.language !== 'Unknown' &&
    current.language !== meta.lang

  const daysSince = Math.floor(
    (Date.now() - new Date(meta.date).getTime()) / (1000 * 60 * 60 * 24),
  )

  const isStale = newFrameworks.length > 0 || languageChanged

  return { isStale, newFrameworks, languageChanged, daysSince }
}

/** Human-readable summary of what changed, e.g. "Prisma, Vitest added; JS → TS" */
export function describeStaleness(result: StalenessResult): string {
  const parts: string[] = []
  if (result.newFrameworks.length > 0) {
    parts.push(`new: ${result.newFrameworks.join(', ')}`)
  }
  if (result.languageChanged) {
    parts.push('language changed')
  }
  return parts.join(' · ')
}
